# Generated by Django 5.1.3 on 2025-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryitem',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
