# Generated by Django 5.1.3 on 2025-01-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_bakeryitem_sales_order_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bakeryitem',
            name='sales',
        ),
    ]
