# Generated by Django 5.1.3 on 2025-01-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_remove_bakeryitem_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
