# Generated by Django 5.1.3 on 2025-01-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_remove_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakeryitem',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
