# Generated by Django 5.1.3 on 2025-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_bakeryitem_sales_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
